apiVersion: apps/v1
kind: Deployment
metadata:
  name: test
spec:
  selector:
    matchLabels:
      app: test
  replicas: 1
  template:
    metadata:
      labels:
        app: test
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
        prometheus.io/path: "/actuator/prometheus"
    spec:
      containers:
        - name: nginx
          image: navjotsrakhra/autoscale-test:1.0.0
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: test
  labels:
    app: test
spec:
  ports:
    - protocol: TCP
      name: http-traffic
      port: 8080
      targetPort: 8080
  selector:
    app: test
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: test-service-monitor
  labels:
    release: prometheus-operator
spec:
  selector:
    matchLabels:
      app: test
  endpoints:
    - port: http-traffic
      path: "/actuator/prometheus"